module.exports = {
  User: require("./User"),
  Alert: require("./Alert"),
  // Etablissement: require("./Etablissement"),
  Responsable: require("./Responsable"),
  Csaio: require("./Csaio"),
  Formateur: require("./Formateur"),
  Academie: require("./Academie"),
  Formation: require("./Formation"),
  Voeu: require("./Voeu"),
  Mef: require("./Mef"),
  Log: require("./Log"),
  Dossier: require("./Dossier"),
  ...require("./events"),
};
