version: "2.4"
services:

  reverse_proxy:
    image: voeux_affelnet_reverse_proxy
    container_name: voeux_affelnet_reverse_proxy
    tty: true
    build:
      context: reverse_proxy
    mem_limit: 96m
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    networks:
      - voeux_affelnet_network
    depends_on:
      - server
      - ui
    environment:
      - PARANOIA=1
      - ANOMALY_INBOUND=5
      - ANOMALY_OUTBOUND=4
      - DNS_SERVER=127.0.0.11
      - PROXY=1
      - ACCESSLOG=/data/access.log
      - ERRORLOG=/data/error.log
      - LOGLEVEL=warn
      - NGINX_ALWAYS_TLS_REDIRECT=false
      - ALLOWED_METHODS=GET HEAD POST OPTIONS PUT DELETE

  ui:
    image: voeux_affelnet_ui
    container_name: voeux_affelnet_ui
    tty: true
    build:
      context: ui
    mem_limit: 256m
    networks:
      - voeux_affelnet_network
    depends_on:
      - server

  server:
    image: voeux_affelnet_server
    container_name: voeux_affelnet_server
    tty: true
    build:
      context: server
    mem_limit: 2g
    restart: unless-stopped
    networks:
      - voeux_affelnet_network
    depends_on:
      - mongodb
    environment:
      - VOEUX_AFFELNET_MONGODB_URI=mongodb://mongodb:27017/voeux_affelnet?retryWrites=true&w=majority
      - VOEUX_AFFELNET_LOG_DESTINATIONS=stdout,mongodb
      - VOEUX_AFFELNET_OUTPUT_DIR=/data

  mongodb:
    image: mongo:5.0.7-focal
    container_name: voeux_affelnet_mongodb
    tty: true
    command: --wiredTigerCacheSizeGB 1 --port 27017
    mem_limit: 2g
    restart: unless-stopped
    networks:
      - voeux_affelnet_network

networks:
  voeux_affelnet_network:
    name: voeux_affelnet_network
