const RelationActions = {
  DELEGATION_CANCELLED_BY_ADMIN: "DELEGATION_CANCELLED_BY_ADMIN",
  DELEGATION_CANCELLED_BY_RESPONSABLE: "DELEGATION_CANCELLED_BY_RESPONSABLE",
  DELEGATION_CREATED_BY_ADMIN: "DELEGATION_CREATED_BY_ADMIN",
  DELEGATION_CREATED_BY_RESPONSABLE: "DELEGATION_CREATED_BY_RESPONSABLE",
  DELEGATION_UPDATED_BY_ADMIN: "DELEGATION_UPDATED_BY_ADMIN",
  DELEGATION_UPDATED_BY_RESPONSABLE: "DELEGATION_UPDATED_BY_RESPONSABLE",

  LIST_AVAILABLE: "LIST_AVAILABLE",
  LIST_DOWNLOADED_BY_DELEGUE: "LIST_DOWNLOADED_BY_DELEGUE",
  LIST_DOWNLOADED_BY_RESPONSABLE: "LIST_DOWNLOADED_BY_RESPONSABLE",

  UPDATED_LIST_AVAILABLE: "UPDATED_LIST_AVAILABLE",
  UPDATED_LIST_DOWNLOADED_BY_DELEGUE: "UPDATED_LIST_DOWNLOADED_BY_DELEGUE",
  UPDATED_LIST_DOWNLOADED_BY_RESPONSABLE: "UPDATED_LIST_DOWNLOADED_BY_RESPONSABLE",
};

const DelegueActions = {
  ACCOUNT_ACTIVATED: "DELEGUE_ACCOUNT_ACTIVATED",
  ACCOUNT_ACTIVATION_EMAIL_AUTOMATIC_RESENT: "DELEGUE_ACCOUNT_ACTIVATION_EMAIL_AUTOMATIC_RESENT",
  ACCOUNT_ACTIVATION_EMAIL_AUTOMATIC_SENT: "DELEGUE_ACCOUNT_ACTIVATION_EMAIL_AUTOMATIC_SENT",
  ACCOUNT_ACTIVATION_EMAIL_MANUAL_RESENT: "DELEGUE_ACCOUNT_ACTIVATION_EMAIL_MANUAL_RESENT",

  ACCOUNT_CONFIRMATION_EMAIL_AUTOMATIC_RESENT: "DELEGUE_ACCOUNT_CONFIRMATION_EMAIL_AUTOMATIC_RESENT",
  ACCOUNT_CONFIRMATION_EMAIL_AUTOMATIC_SENT: "DELEGUE_ACCOUNT_CONFIRMATION_EMAIL_AUTOMATIC_SENT",
  ACCOUNT_CONFIRMATION_EMAIL_MANUAL_RESENT: "DELEGUE_ACCOUNT_CONFIRMATION_EMAIL_MANUAL_RESENT",
  ACCOUNT_CONFIRMED: "DELEGUE_ACCOUNT_CONFIRMED",

  ACCOUNT_EMAIL_UPDATED_BY_ACCOUNT: "DELEGUE_ACCOUNT_EMAIL_UPDATED_BY_ACCOUNT",
  ACCOUNT_EMAIL_UPDATED_BY_ADMIN: "DELEGUE_ACCOUNT_EMAIL_UPDATED_BY_ADMIN",

  LIST_AVAILABLE_EMAIL_AUTOMATIC_RESENT: "LIST_AVAILABLE_EMAIL_AUTOMATIC_RESENT",
  LIST_AVAILABLE_EMAIL_AUTOMATIC_SENT: "LIST_AVAILABLE_EMAIL_AUTOMATIC_SENT",
  LIST_AVAILABLE_EMAIL_MANUAL_RESENT: "LIST_AVAILABLE_EMAIL_MANUAL_RESENT",

  UPDATED_LIST_AVAILABLE_EMAIL_AUTOMATIC_RESENT: "UPDATED_LIST_AVAILABLE_EMAIL_AUTOMATIC_RESENT",
  UPDATED_LIST_AVAILABLE_EMAIL_AUTOMATIC_SENT: "UPDATED_LIST_AVAILABLE_EMAIL_AUTOMATIC_SENT",
  UPDATED_LIST_AVAILABLE_EMAIL_MANUAL_RESENT: "UPDATED_LIST_AVAILABLE_EMAIL_MANUAL_RESENT",
};

const FormateurActions = {};

const ResponsableActions = {
  ACCOUNT_ACTIVATED: "RESPONSABLE_ACCOUNT_ACTIVATED",
  ACCOUNT_ACTIVATION_EMAIL_AUTOMATIC_RESENT: "RESPONSABLE_ACCOUNT_ACTIVATION_EMAIL_AUTOMATIC_RESENT",
  ACCOUNT_ACTIVATION_EMAIL_AUTOMATIC_SENT: "RESPONSABLE_ACCOUNT_ACTIVATION_EMAIL_AUTOMATIC_SENT",
  ACCOUNT_ACTIVATION_EMAIL_MANUAL_RESENT: "RESPONSABLE_ACCOUNT_ACTIVATION_EMAIL_MANUAL_RESENT",

  ACCOUNT_CONFIRMATION_EMAIL_AUTOMATIC_RESENT: "RESPONSABLE_ACCOUNT_CONFIRMATION_EMAIL_AUTOMATIC_RESENT",
  ACCOUNT_CONFIRMATION_EMAIL_AUTOMATIC_SENT: "RESPONSABLE_ACCOUNT_CONFIRMATION_EMAIL_AUTOMATIC_SENT",
  ACCOUNT_CONFIRMATION_EMAIL_MANUAL_RESENT: "RESPONSABLE_ACCOUNT_CONFIRMATION_EMAIL_MANUAL_RESENT",
  ACCOUNT_CONFIRMED: "RESPONSABLE_ACCOUNT_CONFIRMED",

  // ACCOUNT_CREATED: "RESPONSABLE_ACCOUNT_CREATED",

  ACCOUNT_EMAIL_UPDATED_BY_ACCOUNT: "RESPONSABLE_ACCOUNT_EMAIL_UPDATED_BY_ACCOUNT",
  ACCOUNT_EMAIL_UPDATED_BY_ADMIN: "RESPONSABLE_ACCOUNT_EMAIL_UPDATED_BY_ADMIN",

  LIST_AVAILABLE_EMAIL_AUTOMATIC_RESENT: "LIST_AVAILABLE_EMAIL_AUTOMATIC_RESENT",
  LIST_AVAILABLE_EMAIL_AUTOMATIC_SENT: "LIST_AVAILABLE_EMAIL_AUTOMATIC_SENT",
  LIST_AVAILABLE_EMAIL_MANUAL_RESENT: "LIST_AVAILABLE_EMAIL_MANUAL_RESENT",

  UPDATED_LIST_AVAILABLE_EMAIL_AUTOMATIC_RESENT: "UPDATED_LIST_AVAILABLE_EMAIL_AUTOMATIC_RESENT",
  UPDATED_LIST_AVAILABLE_EMAIL_AUTOMATIC_SENT: "UPDATED_LIST_AVAILABLE_EMAIL_AUTOMATIC_SENT",
  UPDATED_LIST_AVAILABLE_EMAIL_MANUAL_RESENT: "UPDATED_LIST_AVAILABLE_EMAIL_MANUAL_RESENT",
};

module.exports = {
  RelationActions,
  DelegueActions,
  FormateurActions,
  ResponsableActions /*, FormateurHistoryItems, ResponsableHistoryItems*/,
};
