FROM node:16-alpine

COPY .yarnrc.yml* /
RUN echo -e "yarnPath: .yarn/releases/yarn-3.3.1.cjs\n\
nodeLinker: node-modules\n\
defaultSemverRangePrefix: ''\n\
" > /.yarnrc.yml ;
WORKDIR /app

VOLUME /data
EXPOSE 5000
CMD yarn install --immutable && yarn debug
