FROM node:20-alpine

WORKDIR /app

ARG VOEUX_AFFELNET_SENTRY_DSN
ARG VOEUX_AFFELNET_ENV
ARG VOEUX_AFFELNET_EMAIL
ENV REACT_APP_VOEUX_AFFELNET_ENV=$VOEUX_AFFELNET_ENV
ENV REACT_APP_VOEUX_AFFELNET_SENTRY_DSN=$VOEUX_AFFELNET_SENTRY_DSN
ENV REACT_APP_VOEUX_AFFELNET_EMAIL=$VOEUX_AFFELNET_EMAIL

RUN corepack enable &&\
  corepack prepare yarn@stable --activate && \
  yarn set version 4.5.0  && \
  yarn config set nodeLinker node-modules && \
  yarn config set defaultSemverRangePrefix '' && \
  yarn config set --home enableTelemetry 0 && \
  yarn config set compressionLevel mixed

EXPOSE 3000

CMD yarn install && yarn start
