name: Yarn CI Server

on: [ push ]
jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: 'server'

    steps:
      - uses: actions/checkout@v4.2.2

      - name: Enable corepack
        run: corepack enable

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'
          cache-dependency-path: '**/yarn.lock'

      # setup .yarnrc.yml
      - name: Create .yarnrc.yml
        run: |
          yarn set version 4.5.0
          yarn config set nodeLinker node-modules
          yarn config set defaultSemverRangePrefix ""
          yarn config set compressionLevel mixed
          yarn config set --home enableTelemetry 0

      # Install dependencies
      - name: Run Yarn Install
        run: |
          yarn install --immutable

      # Lint
      - name: Run Lint
        run: |
          yarn lint

      # Run tests
      - name: Run Tests
        run: |
          yarn test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./.coverage
          name: codecov-server
          verbose: true
